### ISSUE TITLE
The repo blocks should share one horizontal scrollbar

### ISSUE THREAD

**Issue by daniboy** [HeikoBecker/Repograms#29]

**Comment by Suizidhamster** [comment]
I updated my branch for this issue: 416590d86fd3e3b50f83af82ade17111770083d4 .
It's now based on the current master branch and includes the horizontal scroll bar.
I also fixed the issue that it was only working in Firefox and tested it for Chrome and Opera.
So far, only the rounding error remains.

**Comment by daniboy** [comment]
This solution doesn't work for us so well. The scroll bar is relative, not absolute, which seems confusing to us.

I created a static version of a solution that works the way we were thinking:
http://www.cs.ubc.ca/~rodaniel/rg/RepoGrams-scroll.html

What I did there was to reorganize the hierarchy of the elements like so:
![repograms-hierarchy-change](https://cloud.githubusercontent.com/assets/1839738/5846860/415e5782-a17c-11e4-9d40-4c4dce1dddc7.png)

This way the individual block lines can have `overlow: visible` and the container for all block lines can have `overflow: auto`.
This will cause them all to share a single horizontal scroll bar. (after some other CSS changes to the margins, heights, etc.)

And this is how I synchronize the scrollbars between the blocks of the different metrics
```javascript
$('.repo-collection').on('scroll', function () {
    $('.repo-collection').scrollLeft($(this).scrollLeft());
});
```



I didn't want to implement this now because I don't know if it'll interfere with the team's work on multiple metrics. Let me know if you want me to take over this or if you prefer to implement this on your own :)

**Comment by Suizidhamster** [comment]
I thought about this approach as well, as it is also quite easy to implement.
The problem I saw with this was that at some point one would not be able to actually compare different repos with each other, if they have different sizes, as visible in your example as well, when scrolling to the very right. But of course I can't blame you if this is actually what you'd like to have :)
I just had a look at the implementation of the multiple metrics and from what I've seen I'd say it doesn't interfere with this approach.
I could combine the horizontal scrolling with the multiple metrics this weekend, if you're happy with the multiple metrics.

**Comment by bestchai** [comment]
Multiple metrics look great!

Definitely need to be able to scroll the repos simultaneously, even if they
have different sizes (total lengths). Can the scrollbar be pinned to the
largest metric so that it would be possible to see all of the repos before
the scrollbar is over?

ivan.

**Comment by daniboy** [comment]
@bestchai to clarify “Can the scrollbar be pinned to the largest metric” — is the [mockup](http://www.cs.ubc.ca/~rodaniel/rg/RepoGrams-scroll.html) behaving the way you describe or is it different?

**Comment by Suizidhamster** [comment]
I created a new branch for this issue, again, 3b29c472fadf6b3659d36a7ad3d1c90f3de78ba7.
I originally had in mind to base this on the multimetrics-branch, however, this wasn't working for me, so I just adapted things based on the current master.

@daniboy, could you have a look at this and check whether this works as you had in mind? I'm not sure whether I included all CSS changes you mentioned earlier.

**Comment by daniboy** [comment]
Looks good! The design doesn't seem to break with long repo names, etc. so I think it's fine.

Now for the fun part — integrating this into the multimetrics branch :)

**Comment by Suizidhamster** [comment]
I merged this into the multimetrics branch and fixed some issues that came up.

**Comment by daniboy** [comment]
The merge looks good. Thanks!
