### ISSUE TITLE
Reordering the repositories after adding

### ISSUE THREAD

**Issue by daniboy** [HeikoBecker/Repograms#33]
Users should be able to change the order of the repositories with drag-and-drop
(I thought I already opened this issue but couldn't find it. I apologize if this is a duplicate)

**Comment by daniboy** [comment]
The order should only be changeable on the first metric block (e.g. in [this mockup](http://www.cs.ubc.ca/~rodaniel/rg/RepoGrams.html) it should be changeable on “Commit Localization” but not on “Commit Message Length”) and should be linked (so when the order of one metric section is change, the others sync with it)

Ideally we would like it be drag and drop, however with the hierarchy change that I suggested in issue #29 it might be too much work for our tight schedule. If you think it will take too long, we can use buttons/links with up and down arrows instead.

Put the arrows between the remove repository button and the repository name. The arrows should be `display: none` until the user hovers their mouse on the repository name.

e.g.

```
No mouse hover:

[x] sqlitebrowser
[x] vim.js
[x] AudioStreamer
[x] LightTable
[x] html-pipeline



mouse hovers over vim.js:

[x] sqlitebrowser
[x] [↑] [↓] vim.js
[x] AudioStreamer
[x] LightTable
[x] html-pipeline
```

If you *can* do the drag-and-drop use one bi-directional arrow (↕) as the drag target.

**Comment by HeikoBecker** [comment]
Added the arrows as explained by @daniboy 
swaprepos contains a version based on master and as merging went fine, I merged into multimetrics. So multimetrics contains current state of developement.

**Comment by HeikoBecker** [comment]
For displaying on hover there is some angular way of doing it I will investigate

**Comment by daniboy** [comment]
I tested it and it looks like it's working well.
Remaining issues:
* Only display when hovering over the name (can probably be done with simple CSS instead of JS/Angular)
* While you're at it, let's experiment with hiding the [X] button (that removes repos) and making them thinner :) if this looks good, we can leave it as it, if not we would want to remove all the buttons for the non-first metric (which would be a pain, I know)
