### ISSUE TITLE
Highlight the clicked/selected commit

### ISSUE THREAD

**Issue by bestchai** [HeikoBecker/Repograms#69]
Currently, when a commit is clicked a dialog comes up that screens the rest of the page. When this dialog is shown, it's easy to forget/lose track of the commit that was selected (corresponding to the dialog). Therefore, the selected commit block must be somehow highlighted when it is selected.

**Comment by daniboy** [comment]
Since we display multiple metrics, we should also highlight the same commit in the other metrics when hovering over any of them
