### ISSUE TITLE
Make Repograms display multiple Metrics at once

### ISSUE THREAD

**Issue by HeikoBecker** [HeikoBecker/Repograms#74]
As discussed via Hangout, Repograms should be able to display multiple Metrics at once.
Notes will be in the  [wiki](MultiMetrics) .

**Comment by daniboy** [comment]
I fixed most of the dependent issues, except #78 (freezing issue) and #29 (shared horizontal scrollbar) and merged my new metrics to the multimetrics branch.

Do you think you'll have the time this/next week to fix these two (merge in case of the scrollbar) and double check that the design looks close enough to the [mockup](http://www.cs.ubc.ca/~rodaniel/rg/RepoGrams-scroll.html)?
