### ISSUE TITLE
Getting an error when trying to deploy locally

### ISSUE THREAD

**Issue by daniboy** [HeikoBecker/Repograms#76]
When I deploy the multimetric branch on jerry it works well, but when I try to deploy it locally I get the following error message on pre-cache or on a direct manual call to /getGitData. Any ideas why this happens?

```
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "serve.py", line 27, in getGitData
    g = git_graph.GitGraph(git_helper, self.cache, precompute = True)
  File "/var/www/html/scripts/git_graph.py", line 85, in __init__
    self.metric6()
  File "/var/www/html/scripts/git_graph.py", line 196, in metric6
    assert branch_counter &gt;= 1, "There should be at least one branch all the time: branch_counter: {}, commit {}: ".format(branch_counter, self.commit_hashsum[commit_node])
AssertionError: There should be at least one branch all the time: branch_counter: -1, commit 2d1e4e0eeed754ac0ddeb85c2484433b2d4310bf: 
```

**Comment by daniboy** [comment]
I managed to zero in on the problem. Looks like my Docker image has `python-graph-tool` version `2.2.36-1`. On jerry, which is using a cached docker base image to build the repograms docker image with, the version of that package is `2.2.35-1`.
The code breaks with the later version. I can't figure out how to force my image to revert back to `2.2.35-1`, it seems that the repository no longer holds the older version.

This is a critical issue since we can't rely on the cached base docked images to build the tool…

----

What I discovered so far:
(hopefully you can use that to spare some time when working on this)

I manually ran `apt-get upgrade` inside the running docker image on jerry on all packages, and another time on all packages except `python-graph-tool`.

After restarting `myapp` using `supervisorctl` I found that the app works fine when `python-graph-tool` hasn't been updated but crashes when it does. This indicates that there shouldn't be any more problems once any issues revolving the updated version of `python-graph-tool` have been fixed.

Since I did the upgrades inside a running docker container it doesn't affect the cached based images so I can still redeploy to jerry without fixing this bug (however, it still affects my ability to work locally)

----
I've noticed that the package repository for our base image, Ubuntu 14.04, is: `deb http://downloads.skewed.de/apt/trusty trusty universe`. This repo has version `2.2.36-1` of `python-graph-tool`

However, the package repository for the Ubuntu version that I'm running on my own laptop (14.10), which is `deb http://downloads.skewed.de/apt/utopic utopic universe`, has version `2.2.35-1`.

It's weird that the repository for the later Ubuntu version hasn't been updated as well. This is the reason why it took half a day to figure out why the process doesn't crash when I run it locally, but crashes when I run it inside the docker image.

**Comment by Inkane** [comment]
Hi,

thanks for figuring out the cause of this issue. The issue seems to be 
that the topological sort function of graph tool now returns the 
elements in the reversed order 
(https://git.skewed.de/count0/graph-tool/commit/2009aa5d4d5faccee7cd41920af2ddf82c04b805).
Fortunately, this can be easily fixed by checking the value of
graph_tool.__version__ and reversing the result if necessary.

Fabian

**Comment by daniboy** [comment]
Looks like this is fixed.
