### ISSUE TITLE
The order of the metrics should change based on the order of their selection

### ISSUE THREAD

**Issue by daniboy** [HeikoBecker/Repograms#83]
Not on the preset order in which they are described

**Comment by daniboy** [comment]
@Inkane can you take a look at this? This is the only blocking issue before the study and I can't figure it out without jumping through a hoops :)

**Comment by Inkane** [comment]
@daniboy : This should be fixed in the multimetrics branch.

**Comment by daniboy** [comment]
That's great :) I assumed AngularJS has something to make this easier but I couldn't figure it out. Thanks for solving this so quickly!
I also added this sort to the repos-first view based on your solution.
